import DashboardPage from "@/modules/dashboard/Dashboard";
import EntryExitHome from "@/modules/entry-exit/EntryExitHome";
import VehicleEntryPage from "@/modules/entry-exit/VehicleEntryPage";
import VehicleExitPage from "@/modules/entry-exit/VehicleExitPage";
import LoginPage from "@/modules/login/LoginPage";
import WaitingVehiclesPage from "@/modules/waiting-vehicles/WaitingVehiclesPage";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Revitup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <LoginPage/> */}
      {/* <VehicleEntryPage /> */}
      {/* <EntryExitHome/> */}
      {/* <VehicleExitPage/> */}
      {/* <WaitingVehiclesPage /> */}
      <DashboardPage/>
    </>
  );
}
