import Appbar from "@/modules/common/Appbar";
import Layout from "@/modules/common/Layout";
import Navigation from "@/modules/common/Sidebar";
import Head from "next/head";
import React from "react";
import DashboardSidebar from "@/modules/dashboard/DashboardSidebar";
import DashboardMain from "@/modules/dashboard/DashboardMain";

export default function Home() {
  const [drawerOpen, setDrawerOpen] = React.useState<Boolean>(false);
  return (
    <>
      <Head>
        <title>Revitup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Comment  the Layout.Root to see other pages -start  */}
      <Layout.Root
        sx={{
          ...(drawerOpen && {
            height: "100vh",
            overflow: "hidden",
          }),
        }}
      >
        <Layout.Header>
          <Appbar />
        </Layout.Header>
        <Layout.SideNav>
          {/* <Navigation /> */}
          <DashboardSidebar setCurrentPage={undefined} />
        </Layout.SideNav>
        <Layout.Main>
          <DashboardMain />
        </Layout.Main>
      </Layout.Root>
    </>
  );
}
